#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 24 10:51:04 2019

@author: macenrola
"""

def format_gaussian_input_from_xyz(xyz_file):
	"""
	PRE: Takes in a valid xyz file generated by openbabel
	POST: will produce a gaussian input file
	"""
	name=xyz_file.split("/")[-1]
	route="#N PM6D3 opt=(ts, noeigentest, modredundant, calcall, maxcyc=999) freq"
	freeze=" D       2       3       9      10 F"
	checkpoint="%Chk={}.chk".format(name)
	mem="%mem=120gb"
	procs="%NProcShared=24"

# =============================================================================
# 	Fine tuning the charge and multiplicity
# =============================================================================
	if 'diradical' in f or 'N2' in f:
		charge_mult="1 3"
		print "{} is diradical or n2".format(f)
	else:
		charge_mult = "2 1"
		
		
# =============================================================================
# 	Fine tuning the route section
# =============================================================================
	if 'TS' in f:
		route="#n wB97XD/6-31G(d) opt=(ts, noeigentest, modredundant, calcfc, maxcyc=999) maxdisk=100GB freq"
	else:
		route="#n wB97XD/6-31G(d) opt=(modredundant, maxcyc=999) maxdisk=100GB freq"

	with open(xyz_file, 'rb') as r:
		coords = r.readlines()[2:]

	with open(xyz_file+".com", "wb") as w:
		w.write(procs+"\n")
		w.write(checkpoint+"\n")
		w.write(mem+"\n")
		w.write(route+"\n\n")
		w.write(name+"\n\n")
		w.write(charge_mult+"\n")
		w.writelines(coords)
		w.write("\n")
		# w.write("notatoms=1-{}\n".format(len(coords)-126))
		w.write(freeze+"\n")
		w.write("\n")

if __name__ == "__main__":
	import sys
	
	if len(sys.argv)==1:
		print "Please provide input files"
	if len(sys.argv)==2:
		format_gaussian_input_from_xyz(sys.argv[1])
	if len(sys.argv)>2:
		for f in sys.argv[2:]:
			format_gaussian_input_from_xyz(f)